name: CI (Swift DEV snapshots + TensorFlow C 2.19.0)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: swift ${{ matrix.swift }}-DEV on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-15]
        swift: ['6.2']   # add '6.3' when you're ready

    env:
      # Keep nvcc/nvc++ from hijacking C/C++ compiles under SwiftPM
      CC: clang
      CXX: clang++
      CUDAHOSTCXX: ""
      # Homebrew QoL
      HOMEBREW_NO_ANALYTICS: "1"
      HOMEBREW_NO_AUTO_UPDATE: "1"
      HOMEBREW_NO_INSTALL_CLEANUP: "1"
      HOMEBREW_NO_ENV_HINTS: "1"

    steps:
      - uses: actions/checkout@v4

      # Swift DEVELOPMENT snapshot toolchain (macOS & Linux)
      - name: Setup Swift (development snapshot)
        uses: SwiftyLab/setup-swift@v1.11.0
        with:
          swift-version: ${{ matrix.swift }}
          development: true
          check-latest: true
      - name: Show Swift toolchain
        run: swift --version

      # (Optional) feature sanity: Differentiable Programming flag
      - name: Check Differentiable feature availability
        run: |
          swift -print-supported-features | (grep -i "differentiable" || true)

      # Enable Homebrew on Ubuntu runners (preinstalled but not on PATH)
      - name: Setup Homebrew (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu-')
        uses: Homebrew/actions/setup-homebrew@main

      # Install TensorFlow C via Homebrew on both OSes and assert 2.19.0
      - name: Install libtensorflow 2.19.0
        shell: bash
        run: |
          set -euxo pipefail
          brew update
          brew install libtensorflow
          PREFIX="$(brew --prefix libtensorflow)"

          # Version check without JSON (handles 2.19.0_1 etc.)
          ver="$(brew list --versions libtensorflow | awk '{print $2}')"
          echo "Installed libtensorflow version: $ver"
          case "$ver" in
            2.19.0*) : ;;
            *) echo "ERROR: expected 2.19.0 but got $ver" >&2; exit 1 ;;
          esac

          # Export for Package.swift (manifest reads these)
          echo "LIBTENSORFLOW_INCLUDEDIR=$PREFIX/include" >> "$GITHUB_ENV"
          echo "LIBTENSORFLOW_LIBDIR=$PREFIX/lib" >> "$GITHUB_ENV"

          # Ensure runtime can find libtensorflow.{so,dylib}
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "LD_LIBRARY_PATH=$PREFIX/lib:${LD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"
          else
            echo "DYLD_LIBRARY_PATH=$PREFIX/lib:${DYLD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"
          fi

      # Cache SwiftPM build artifacts
      - name: Cache .build
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-swift-${{ matrix.swift }}-DEV-build-${{ hashFiles('**/Package.resolved', 'Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-${{ matrix.swift }}-DEV-build-
            ${{ runner.os }}-swift-${{ matrix.swift }}-

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

      - name: Sanity (tf4swift-opgen --help)
        run: ./.build/debug/tf4swift-opgen --help || true

      - name: Upload opgen artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tf4swift-opgen-${{ matrix.os }}-swift-${{ matrix.swift }}-DEV
          path: .build/debug/tf4swift-opgen
