name: CI (Swift DEV snapshots + TensorFlow C 2.19.0)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: swift ${{ matrix.swift }}-DEV on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-15]
        swift: ['6.2']   # add '6.3' when you're ready

    # Keep nvcc/nvc++ from hijacking SPM's C/C++ compiles
    env:
      CC: clang
      CXX: clang++
      CUDAHOSTCXX: ""
      HOMEBREW_NO_ANALYTICS: "1"
      HOMEBREW_NO_AUTO_UPDATE: "1"

    steps:
      - uses: actions/checkout@v4

      # Swift DEVELOPMENT snapshots (macOS & Linux)
      # See: https://github.com/marketplace/actions/setup-swift-environment-for-macos-linux-and-windows
      - name: Setup Swift (development snapshot)
        uses: SwiftyLab/setup-swift@v1.11.0
        with:
          swift-version: ${{ matrix.swift }}
          development: true
          check-latest: true
      - name: Show Swift toolchain
        run: swift --version

      # (Optional) feature sanity: Differentiable Programming flag
      - name: Check Differentiable feature availability
        run: |
          swift -print-supported-features | (grep -i "differentiable" || true)

      # Enable Brew on Ubuntu runners (preinstalled but not on PATH)
      # Correct action path: Homebrew/actions/setup-homebrew@main
      - name: Setup Homebrew (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu-')
        uses: Homebrew/actions/setup-homebrew@main

      # Install TensorFlow C via Homebrew on both OSes and pin to 2.19.0
      - name: Install libtensorflow 2.19.0
        shell: bash
        run: |
          set -euxo pipefail
          brew update
          brew install libtensorflow
          PREFIX="$(brew --prefix libtensorflow)"

          # Verify we got exactly 2.19.0 (fail if Homebrew moves ahead)
          ver=$(brew info --json=v2 libtensorflow | python3 - <<'PY'
          import sys, json
          j = json.load(sys.stdin)
          print(j["formulae"][0]["versions"]["stable"])
          PY
          )
          echo "Installed libtensorflow version: $ver"
          test "$ver" = "2.19.0"

          # Export for Package.swift (your manifest reads these)
          echo "LIBTENSORFLOW_INCLUDEDIR=$PREFIX/include" >> "$GITHUB_ENV"
          echo "LIBTENSORFLOW_LIBDIR=$PREFIX/lib" >> "$GITHUB_ENV"

          # Ensure runtime can find libtensorflow.{so,dylib}
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "LD_LIBRARY_PATH=$PREFIX/lib:${LD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"
          else
            echo "DYLD_LIBRARY_PATH=$PREFIX/lib:${DYLD_LIBRARY_PATH:-}" >> "$GITHUB_ENV"
          fi

      # Cache SwiftPM build artifacts
      - name: Cache .build
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-swift-${{ matrix.swift }}-DEV-build-${{ hashFiles('**/Package.resolved', 'Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-swift-${{ matrix.swift }}-DEV-build-
            ${{ runner.os }}-swift-${{ matrix.swift }}-

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v

      - name: Sanity (tf4swift-opgen --help)
        run: ./.build/debug/tf4swift-opgen --help || true

      - name: Upload opgen artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tf4swift-opgen-${{ matrix.os }}-swift-${{ matrix.swift }}-DEV
          path: .build/debug/tf4swift-opgen
